#define Borrar_Certificado	102
#define Borrar_Póliza	103
#define Categorías_de_Flujos_de_Trabajo	104
#define Ciudades	105
#define Flujos_de_Trabajo_y_Correspondencia	107
#define Departamentos	106
#define Grupos_de_Usuarios	108
#define Importar_Certificados	109
#define Importar_Facturas	110
#define Importar_Pólizas	111
#define Importar_Siniestros	112
#define Municipios	113
#define Parámetros_Generales	114
#define Skins	115
#define Traslado_de_Clientes	116
#define Ubicaciones_de_Entrega	117
#define Unificar_Productos	118
#define Usuarios	119
#define Zonas_y_Rutas	120
#define Aseguradoras	201
#define Bancos	202
#define Estado_de_Personas	203
#define Formas_de_Pago	204
#define Parentescos	205
#define Productos	206
#define Ramos	207
#define Tipo_de_Vendedores	208
#define Tipos_de_Gastos	209
#define Tipos_de_Gestiones	210
#define Vendedores	211
#define Notificaciones	212
#define Tipos_de_Pago	213
#define Búsqueda_de_Bienes	500
#define Cancelar_Póliza	501
#define Comparativo_de_Ofertas	502
#define Condiciones_Especiales	503
#define Detalle_de_Clientes	504
#define Detalle_de_Vencimientos	505
#define Gestión_de_Pólizas	506
#define Histórico_de_Pólizas	507
#define Ofertas	508
#define Planes_de_Seguros	509
#define Pólizas_de_Seguros	510
#define Reactivación_de_Pólizas	511
#define Registro_de_Clientes	512
#define Renovación_de_Pólizas	513
#define Reporte_de_Clientes_con_Pago_a_Tarjetas	514
#define Reporte_de_Gestiones_de_Pólizas_Realizadas	515
#define Reporte_de_Gestiones_Pendientes	516
#define Reporte_de_Ofertas_Pendientes	517
#define Reporte_de_Pólizas_Canceladas	518
#define Reporte_de_Pólizas_con_Archivos_Digitales	519
#define Reporte_de_Pólizas_Emitidas	520
#define Reporte_de_Pólizas_por_Vencer	521
#define Búsqueda_de_Bienes1	522
#define Cancelar_Póliza1	523
#define Comparativo_de_Ofertas1	524
#define Condiciones_Especiales1	525
#define Detalle_de_Clientes1	526
#define Detalle_de_Vencimientos1	527
#define Gestión_de_Pólizas1	528
#define Histórico_de_Pólizas1	529
#define Ofertas1	530
#define Planes_de_Seguros1	531
#define Pólizas_de_Seguros1	532
#define Reactivación_de_Pólizas1	533
#define Registro_de_Clientes1	534
#define Renovación_de_Pólizas1	535
#define Reporte_de_Clientes_con_Pago_a_Tarjetas1	536
#define Reporte_de_Gestiones_de_Pólizas_Realizadas1	537
#define Reporte_de_Gestiones_Pendientes1	538
#define Reporte_de_Ofertas_Pendientes1	539
#define Reporte_de_Pólizas_Canceladas1	540
#define Reporte_de_Pólizas_con_Archivos_Digitales1	541
#define Reporte_de_Pólizas_Emitidas1	542
#define Reporte_de_Pólizas_por_Vencer1	543
#define Bitácora_de_Actividades	101
#define Administración_de_Facturas	301
#define Análisis_Recuperación_de_Mora	302
#define Anulación_de_Facturas	303
#define Anulación_de_Pagos	304
#define Avisos_de_Cobro	305
#define Cambiar_Número_de_Factura	306
#define Cartas_de_Vencimiento_de_Tarjetas_de_Crédito	307
#define Detalle_Depósito_Clientes	308
#define Estado_de_Cuenta_Póliza	309
#define Generar_Estados_Cuenta_Clientes	310
#define Gestión_de_Cartera	311
#define Listado_de_Anulaciones_de_Facturas_Créditos	312
#define Listado_de_Emisión_de_Facturas_Créditos	313
#define Listado_de_Pagos_Emitidos	314
#define Notas_de_Abono	315
#define Notas_de_Crédito	316
#define Registro_de_Pagos	317
#define Registro_Depósitos	318
#define Reporte_de_Gestiones_Pendientes11	319
#define Reporte_de_Gestiones_Realizadas	320
#define Reporte_de_Primas_Pendientes	321
#define Reporte_de_Primas_Pendientes_por_Cliente	322
#define Análisis_de_Ingresos	401
#define Anulación_de_Recibos	402
#define Aplicación_de_Recibos	403
#define Cierre_de_Caja	404
#define Detalle_de_Envíos	405
#define Envíos_Aseguradora	406
#define Listado_de_Recibos_sin_Aplicar	407
#define Listados_de_Ingresos	408
#define Recibos_de_Ingreso	409
#define Reporte_de_Cierre_de_Caja	410
#define Cambio_de_Comisiones	601
#define Estadísticas_Comisiones	602
#define Estado_de_Cuenta	603
#define Estado_de_Cuenta_Vendedores	604
#define Listado_de_Comisiones_por_Producto	605
#define Movimientos_Comisiones	606
#define Operaciones_Comisiones	607
#define Pagos_Aseguradoras	608
#define Resumen_de_Comisiones	609
#define Estadísticas_Metas	701
#define Estadísticas_Pólizas	702
#define Estadísticas_Técnicas	703
#define Generar_Metas	704
#define Gráfica_General	705
#define Metas	706
#define Producción_Clientes	707
#define Resumen_Producción	708
#define Siniestralidad_Clientes	709
#define Anulación_de_Siniestros	801
#define Calculo_de_Pre_Liquidación	802
#define Consulta_de_Siniestros	803
#define Declaración_de_Reclamos_de_Seguros	804
#define Detalle_de_Siniestros	805
#define Generar_Envíos	806
#define Gestión_de_Siniestros	807
#define Pago_Deudores	808
#define Pagos_de_Siniestros	809
#define Planes_de_Siniestros	810
#define Pre_Certificaciones	811
#define Registro_de_Asegurados_Póliza	812
#define Reporte_de_Gestiones_Pendientes2	813
#define Reporte_de_Gestiones_Realizadas1	814
#define Reporte_de_Pre_Certificaciones	815
#define Reporte_de_Saldos_Deudores_Varios	816
#define Reporte_de_Seguimientos	817
#define Reporte_de_Siniestro	818
#define Seguimiento_Siniestros	819
#define Agenda_de_Trabajo	901
#define Análisis_de_Flujos_de_trabajo	902
#define Anular_Documentos	903
#define Asignación_de_Flujos	904
#define Continuar_Flujo	905
#define Control_de_Correspondencia	906
#define Despacho_Simple	907
#define Detalle_de_Correspondencia	908
#define Documentos_no_Entregados	909
#define Generar_Documentos	910
#define Iniciar_un_Flujo	911
#define Re_Asignación_de_Flujos	912
#define Recepción_de_Documentos	913
#define Recepción_Simple	914
#define Reporte_de_Correspondencia_de_Salida	915
#define Resumen_de_Correspondencia	916
#define Rutear_Documentos	917
#define Formularios_Aseguradoras	820
#define Reclamos_de_Gastos_Médicos	821
